[Config]
PreferredCodec=VP61
# Folder is relative to Res/Userdata
Folder=Movies
FilenameBase=movie
NoFillFrames=0
AudioStereoOutput=1 
AudioRateDivisor=1 

GlobalSettings		= reset, vbr:1, fps:30, keyinterval:60, mode:1, datarate:0
SmallSettings		= size: 854x480
MediumSettings		= size: 960x540
LargeSettings		= size: 1280x720
LowQualitySettings	= minq: 6, maxq: 14, mode:0
MediumQualitySettings	= minq: 4, maxq: 10, fps:30, mode:0
HighQualitySettings	= minq: 2, maxq: 8, fps:30, keyinterval: 60
SmallLowSettings		= datarate: 2500
SmallMediumSettings	= datarate: 4000
SmallHighSettings		= datarate: 6000
MediumLowSettings	= datarate: 4000
MediumMediumSettings	= datarate: 7000
MediumHighSettings	= datarate: 10000
LargeLowSettings	= datarate: 8000
LargeMediumSettings	= datarate: 12000
LargeHighSettings	= datarate: 16000

AllowAntialiasing=1

[Codecs]
0=VP61